using Bankomaten.Data;
using Bankomaten.Domain;

namespace Bankomaten.Services;

public class UserManagement
{
    /// <summary>
    /// A dictionary containing user data, where the key is a unique identifier (byte)
    /// and the value is a User object. This dictionary is initialized with pre-seeded user data
    /// generated by the SeedData.GenerateUsers() method.
    /// </summary>
    public Dictionary<byte, User> users;

    public UserManagement(Dictionary<byte, User> users)
    {
        this.users = users;
    }

    /// <summary>
    /// Finds a user by their username from the dictionary of users.
    /// </summary>
    /// <returns>
    /// Returns a User object if a user with the specified username is found;
    /// otherwise, returns null.
    /// </returns>
    public User? FindUser(string username)
    {
        //checks if the username matches any user and returns the user if it does. and if not then null
        foreach (User user in users.Values)
        {
            if (user.UserName == username)
            {
                return user;
            }
        }

        return null;
    }

    /// <summary>Authenticates a user by verifying the provided username and PIN.</summary>
    /// <returns> Returns true if the username and PIN match a user in the stored user data; otherwise, false.</returns>
    public bool Authenticate(string username, string pin)
    {
        //checks if the username and pin match any user in the dictionary and returns the user if they do, null otherwise
        foreach (User user in users.Values)
        {
            if (user.UserName == username && user.Pin == pin)
            {
                return user;
            }
        }

        return null;
    }
}